name: CheckOut
on: "push"

jobs:
    Checkout-using-actions:
        runs-on: ubuntu-latest
        steps:
            - name: list
              run: ls -a 
            - name: Using Checkout action
              uses: actions/checkout@v3
            - name: After listing
              run: ls -a

    Code-checkout:
        runs-on: ubuntu-latest
        steps:
            - name: list
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List all the files
              run: ls -a