name: Executing the commands
on: [ push ]

jobs:
    Shell-command-execution:
        runs-on: ubuntu-latest
        steps:
            - name: Executing
              run: |
                pwd
                ls -a
                echo  $GITHUB_SHA
                echo  $GITHUB_WORKSPACE
                echo  $GITHUB_REPOSITORY

    Window-command-execution-w:
        runs-on: ubuntu-latest
        steps:
            - name: Executing
              run: |
                pwd
                ls -a
                echo  $GITHUB_SHA
                echo  $GITHUB_WORKSPACE
                echo  $GITHUB_REPOSITORY