name: Executing the commands
on: [ push ]

jobs:
    Shell-command-execution:
        runs-on: ubuntu-latest
        steps:
            - name: Executing
              run: |
                pwd
                ls -a
                echo  $GITHUB_SHA
                echo  $GITHUB_WORKSPACE
                echo  $GITHUB_REPOSITORY

    Window-command-execution-w:
        runs-on: windows-latest
        needs: Shell-command-execution
        steps:
            - name: Executing
              run: |
                Get-Location
                dir
                echo  $env:GITHUB_SHA
                echo  $env:GITHUB_WORKSPACE
                echo  $env:GITHUB_REPOSITORY

            - name: Python
              shell: python
              run: |
                import platform
                print(platform)