name: Manual_trigger
on:
    workflow_dispatch:
        inputs:
            string:
                description: The input is string
                type: string
                required: true
                default: "Default values"


jobs:
    manual_trigger:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF