name: workflow Commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Setting an error message
              run: echo "::error::Missing semicolon"
            - name: Setting an error message
              run: echo "::error title= Error title, file=app.js, line=2, endLine=3 col=5, endcolumn=7::Missing Semicolon"
            - name: Setting an debug message
              run: echo "::error title= debug title, file=app.js, line=2, endLine=3 col=5, endcolumn=7::Missing Semicolon " 